src/data/courses.json
=> Add Interneting Is Hard

package-lock.json, src/data/categories.json, src/data/courses.json
@Leocardoso94 I added a course on creating social network using Laravel and PHP by Codecourse.com
=> Created one category for Laravel and added one course to the category

src/data/courses.json
Added Udacity's free 2-week Intro to Javascript Course
=> Added Udacity - Intro to Javascript

src/data/categories.json, src/data/courses.json
Found a helpful course for beginners to the python web framework: Django! Hope this helps (:
Cheers,
Jon
=> Added new course for beginners to Django

src/data/courses.json
=> Adding django girls tutorial

src/data/courses.json
added udacity intro to html and css, js courses
=> added js,html and css courses

src/data/courses.json
Adding the Tango with Django guide to the courses.
=> issue #1 - Adding Tango with Django to courses

src/data/courses.json
=> Add Redux course

src/data/courses.json
I've discovered this nice little course about CSS layout that I'd thought I'd add it to your collection.
=> add learnlayout.com

src/data/courses.json
It's a Udemy Course About Vue.js 100% off
=> Add new Vue.js Course with 100% off

src/data/courses.json
Hi folks! I've added this course (https://www.udemy.com/react-16/) to React's list. I hope it helps! ;)
=> Add a new React course

src/data/courses.json
Just added Real Time Chat apps tutorial, based on Node.js
=> Updated courses.json

src/data/categories.json
Added a category of Swift language
=> Category - Swift

src/data/categories.json
=> Category - Rails

src/data/categories.json
Added category materialize into project.
For now, the icon of this category is from http://vorillaz.github.io/devicons/#/cheat .
=> Category - Materialize

src/data/courses.json
Adding course details for Intro to Python for Data Science, please check and accept the Pull request
=> Adding course details for Intro to Python for Data Science

src/data/courses.json
Adding course details for Try Git, please check and accept the Pull request
=> Adding course details for Try Git

src/data/courses.json
Adding MongoDB University link where you can find MongoDB related courses, please check and accepts the Pull request
=> Adding MongoDB University link where you can find MongoDB related courses

src/data/courses.json
Adding RailsCasts link, it is not free courses site but it contains free screencast. Therefore adding it here. Please check and accept the Pull request.
=> Adding RailsCasts link

src/data/courses.json
Adding Angular 2 Tutorial playlist link, please check and accept Pull request
=> Adding Angular 2 Tutorial playlist link

src/data/courses.json
Adding Express Foundation course link, please check and accept the Pull request.
=> Adding Express Foundation course link

src/data/courses.json
Adding jQuery learning course links - Try jQuery by Codeschool & Introduction to jQuery by Codecademy. Please check and accept the Pull request
=> Adding jQuery learning course links

src/data/courses.json
Adding Laravel course link from CodeSchool, please check and accept Pull-request
=> Adding Laravel course

README.md
I have updated description in README.md file. Please check and accept the Pull-request. I will improve and update the README as soon as I get more time.
=> Updating description in README.md

src/data/categories.json, src/data/courses.json
Adding DotNET category and course link related to it, please check and accept the Pull request.
=> Adding DotNET category and course related to it

CONTRIBUTING.md, README.md
Adding few Github badges to README.md, content improvements in README and CONTRIBUTING file. Please check and accept the Pull request.
=> Improvements in README.md and CONTRIBUTING.md file

CONTRIBUTING.md
Fixing broken link in CONTRIBUTING.md file, Please check and accept Pull request.
=> Fixing broken link

src/data/courses.json
Adding Rect foundation course, please check and accept Pull request.
=> Adding Rect foundation course

src/data/courses.json
Adding Node and MongoDB Foundation course link, please check and accept Pull request.
=> Adding Node Foundation course

src/data/courses.json
Free ebook to learn plain React while building on larger application on 200 pages. At this point in time, it was downloaded by ~13.000 people and I hope it is a great addition for newcomers to React :)
=> Adding "The Road to learn React"

src/data/courses.json
Adding Python, Ember & PHP beginner course links from CodeSchool, please check and accept Pull request.
=> Adding Python, Ember & PHP course links

src/data/courses.json
Adding tutorial link "Python tutorials step by step". please check and accept the Pull request.
=> Adding Python course

src/data/courses.json
Adding course Introduction to Node.js, please check and accept the Pull request. :)
=> Adding course Introduction to Node.js

src/data/courses.json
Adding Git course from Progate and added a category for the dotnet course. Please check and accept the Pull request
=> Adding Git course

src/data/courses.json
Adding course Introduction to Git for Data Science, please check and accept PR
=> Adding course Introduction to Git for Data Science

src/data/courses.json
Adding Learning Vue 1.0: Step By Step course, please check and accept PR.
=> Adding Learning Vue 1.0: Step By Step

src/data/courses.json
Adding Ruby weekly newsletter link, please check and accept PR.
=> Adding Ruby weekly newsletter link

src/data/courses.json
Adding Powering Up With React course, please check and accept the pull request.
=> Adding Powering Up With React course

src/data/courses.json
The link for the course https://bogdan-lyashenko.github.io/Under-the-hood-ReactJS/
=> Added Under-the-hood:REACTJS course

404.html, src/template.html
Reverts Leocardoso94/Free-Courses#90
=> Revert "GitHub pages spa routing hack"

src/data/courses.json
Added Kent C. Dodds amazing course to learn about git, github and contributing to open source.
https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
=> Added git open source course by Kent C. Dodds

src/data/categories.json, src/data/courses.json
Added an awesome WordPress introductory course by Tania Rascia.
https://www.taniarascia.com/developing-a-wordpress-theme-from-scratch/
#97
=> Added WordPress category and a course for it

src/data/courses.json
Added The Beginner's Guide to React which I found very helpful when learning.
https://egghead.io/courses/the-beginner-s-guide-to-react
=> Added The Beginner's Guide to React

src/data/categories.json, src/data/courses.json
Add new category and also new linux course
=> add category - Linux

src/data/courses.json
A Complete Beginner's Guide to Django that helped me out a lot when I started coding
=> Added a free Django course by Vitor Freitas

src/data/courses.json
This course is very informative and from beginner to intermediate level. The author has more than 230K+ subscribers on youtube.
=> Add a new Materialize course.

src/data/courses.json
Add a new free PHP course available on youtube. The author has around 130k subscribers on youtube.
=> Add a new PHP course

src/data/courses.json
Inclusão de novo curso na categoria Python.
=> Adicionei Python3 na Web com Django
